<?php

namespace App\Permission;

class PermissionConst
{
    // const GESTION_MENU = 'gestion_menu';

    const GESTION_TIPO_CONTRATO = 'GESTION_TIPO_CONTRATO';
    const GESTION_ROLES = 'GESTION_ROLES';
    const GESTION_ROL_PERMISOS = 'GESTION_ROL_PERMISOS';
    const GESTION_USUARIO = 'GESTION_USUARIO';
    const GESTION_PROCESOS = 'GESTION_PROCESOS';
    const GESTION_TIPO_DOCUMENTOS = 'GESTION_TIPO_DOCUMENTOS';
    const GESTION_MEDIO_PAGO = 'GESTION_MEDIO_PAGO';
    const GESTION_TIPO_PAGO = 'GESTION_TIPO_PAGO';
    const GESTION_TIPO_TRANSACCION = 'GESTION_TIPO_TRANSACCION';
    const GESTION_CONTRATACION = 'GESTION_CONTRATACION';
    const GESTION_CONTRATOS = 'GESTION_CONTRATOS';
    const GESTION_PAGOS_CONTRATOS = 'GESTION_PAGOS_CONTRATOS';
    const GESTION_LABORAL = 'GESTION_LABORAL';
    const GESTION_PAGOS_ADICIONALES = 'GESTION_PAGOS_ADICIONALES';
    const GESTION_COMPRAS = 'GESTION_COMPRAS';
    const GESTION_PAGOS_COMPRAS = 'GESTION_PAGOS_COMPRAS';
    const GESTION_PLANES = 'GESTION_PLANES';
    const GESTION_PRODUCTOS_EMPRESARIALES = 'GESTION_PRODUCTOS_EMPRESARIALES';
    const GESTION_CONEXIONES = 'GESTION_CONEXIONES';
    const GESTION_SOLICITUDES_PRODUCTOS = 'GESTION_SOLICITUDES_PRODUCTOS';
    const GESTION_CUENTAS_PENDIENTES = 'GESTION_CUENTAS_PENDIENTES';
    const GESTION_APORTES_SOCIOS = 'GESTION_APORTES_SOCIOS';
    const GESTION_CHAT = 'GESTION_CHAT';
    const GESTION_NOMINA = 'GESTION_NOMINA';

    const GESTION_PUNTO_VENTAS = 'GESTION_PUNTO_VENTAS';

    /** Aula Virtual - Instructor SENA */
    const AULA_VIRTUAL_INSTRUCTOR = 'AULA_VIRTUAL_INSTRUCTOR';

    /** Aula Virtual - Aprendiz */
    const AULA_VIRTUAL_APRENDIZ = 'AULA_VIRTUAL_APRENDIZ';

    const GESTION_SEGUIMIENTO_ASPIRANTES = 'GESTION_SEGUIMIENTO_ASPIRANTES';

    /** Configuración de credenciales de Meta WhatsApp Cloud API (TelecomConfig) */
    const GESTION_TELECOM_CONFIG = 'GESTION_TELECOM_CONFIG';

    /** Estadísticas de mensajes WhatsApp del módulo Seguimiento de Aspirantes (solo lectura). */
    const GESTION_ESTADISTICAS_WHATSAPP_SENA = 'GESTION_ESTADISTICAS_WHATSAPP_SENA';

    /**
     * Módulo administrativo de Planes de Mensajes (Administrador VT).
     * Permiso ÚNICO del módulo: cubre sus cinco pestañas —Solicitudes,
     * Administración de Planes, Dashboard, Historial de Facturación y
     * Configuración de Pagos—. Quien tiene el módulo, lo tiene entero.
     */
    const GESTION_SOLICITUDES_PLANES = 'GESTION_SOLICITUDES_PLANES';
}

