<?php

namespace App\Permission;

class PermissionConst
{
    // const GESTION_MENU = 'gestion_menu';

    const GESTION_TIPO_CONTRATO = 'GESTION_TIPO_CONTRATO';
    const GESTION_ROLES = 'GESTION_ROLES';
    const GESTION_ROL_PERMISOS = 'GESTION_ROL_PERMISOS';
    const GESTION_USUARIO = 'GESTION_USUARIO';
    const GESTION_PROCESOS = 'GESTION_PROCESOS';
    const GESTION_TIPO_DOCUMENTOS = 'GESTION_TIPO_DOCUMENTOS';
    const GESTION_MEDIO_PAGO = 'GESTION_MEDIO_PAGO';
    const GESTION_TIPO_PAGO = 'GESTION_TIPO_PAGO';
    const GESTION_TIPO_TRANSACCION = 'GESTION_TIPO_TRANSACCION';
    const GESTION_CONTRATACION = 'GESTION_CONTRATACION';
    const GESTION_CONTRATOS = 'GESTION_CONTRATOS';
    const GESTION_PAGOS_CONTRATOS = 'GESTION_PAGOS_CONTRATOS';
    const GESTION_LABORAL = 'GESTION_LABORAL';
    const GESTION_PAGOS_ADICIONALES = 'GESTION_PAGOS_ADICIONALES';
    const GESTION_COMPRAS = 'GESTION_COMPRAS';
    const GESTION_PAGOS_COMPRAS = 'GESTION_PAGOS_COMPRAS';
    const GESTION_PLANES = 'GESTION_PLANES';
    const GESTION_PRODUCTOS_EMPRESARIALES = 'GESTION_PRODUCTOS_EMPRESARIALES';
    const GESTION_CONEXIONES = 'GESTION_CONEXIONES';
    const GESTION_SOLICITUDES_PRODUCTOS = 'GESTION_SOLICITUDES_PRODUCTOS';
    const GESTION_CUENTAS_PENDIENTES = 'GESTION_CUENTAS_PENDIENTES';
    const GESTION_APORTES_SOCIOS = 'GESTION_APORTES_SOCIOS';
    const GESTION_CHAT = 'GESTION_CHAT';
    const GESTION_NOMINA = 'GESTION_NOMINA';

    const GESTION_PUNTO_VENTAS = 'GESTION_PUNTO_VENTAS';

    

}
